name: BlockTest
version: 1.3.0-SNAPSHOT
description: A simple test of the BlockPatcher.
author: Comphenix
website: http://www.comphenix.net/BlockTestMod

main: com.comphenix.blocktest.BlockTestMod
depend: [BlockPatcher]
database: false