name: BlockPatcher
version: 1.3.0-SNAPSHOT
description: Allow unmodified clients to connect to a server with custom blocks.
author: Comphenix
website: http://www.comphenix.net/BlockPatcher

main: com.comphenix.blockpatcher.PatcherMod
depend: [ProtocolLib]
database: false